import assert from 'node:assert/strict';
import {optionHistory} from './option-history.mjs';
const asOf='2026-09-30T12:00:00Z';
const order=(id,contract,effect,side,quantity,premium,date)=>({id,state:'filled',chain_symbol:'TEST',quantity,processed_premium:premium,direction:side==='sell'?'credit':'debit',last_transaction_at:date,legs:[{option_id:contract,option_type:'call',strike_price:'50',expiration_date:'2026-10-16',position_effect:effect,side}]});
const a=order('a','old','open','sell',2,400,'2026-09-01');
const b=order('b','old','close','buy',1,50,'2026-09-05');
const c=order('c','new','open','sell',1,900,'2026-09-06');
let h=optionHistory([a,b,c],null,asOf);
assert.equal(h.trades[0].net,150,'open contract on same stock must not inflate closed P&L');
assert.equal(h.trades[0].opening,200,'partial close allocates only matched opening cost');
assert.equal(h.premiumYTD,1300);
assert.deepEqual(optionHistory([a,b,c],h,asOf),h,'repeated refresh is idempotent');
assert.deepEqual(optionHistory([],h,asOf),h,'missing fetch retains ledger');
const d=order('d','old','close','buy',1,75,'2026-09-07');
h=optionHistory([d],h,asOf);
assert.equal(h.trades[0].net,125,'rolling window keeps original opening basis');
assert.equal(h.trades.length,2);
assert.equal(optionHistory([b],null,asOf).trades[0].net,null,'unknown basis never becomes a gain');
const long=optionHistory([order('x','long','open','buy',1,100,'2026-09-01'),order('y','long','close','sell',1,40,'2026-09-02')],null,asOf);
assert.equal(long.trades[0].net,-60);assert.equal(long.premiumYTD,null);
assert.equal(optionHistory([a],null,'2027-01-01').trades.length,0,'passing expiry never implies worthless settlement');
assert.equal(optionHistory([a],null,'2027-01-01').premiumYTD,null);
assert.equal(optionHistory([{...a,legs:[...a.legs,...a.legs]}],null,asOf).unresolved,1);
assert.equal(optionHistory([{...a,processed_premium:null}],null,asOf).unresolved,1);
console.log('Option history tests passed');
