import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const ctx={fmtD:n=>'$'+n.toFixed(2)};vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('function optIncomeHistory('),html.indexOf('function renderOptions(')),ctx);
const broker={source:'robinhood',year:'2026 YTD',asOf:'2026-09-30',accounts:{main:{options:1426}}};
const ledger={version:2,asOf:'2026-09-30',premiumYTD:2498,trades:[{symbol:'AMC',date:'2024-05-17',net:-61}],unresolved:0,pendingResolution:0};
let out=ctx.optIncomeHistory({incomeHistory:ledger},broker);
assert(out.includes('No matched 2026 results'));
assert(!out.includes('Matched results · 2026'));
assert(out.includes('Other years · 1'));
assert(out.includes('Excluded from 2026 totals'));
assert(out.includes('not profit'));
ledger.trades.push({symbol:'TEST',date:'2026-09-18',net:400});
out=ctx.optIncomeHistory({incomeHistory:ledger},broker);
assert(out.includes('$1026.00'),'difference uses current-year results, excludes old loss');
assert(out.includes('2026 monthly matched results'));
assert(!out.includes('2024-05<br>'));
ledger.awaitingSettlement=[{symbol:'<script>',date:'2026-09-25',opening:300,net:null}];
out=ctx.optIncomeHistory({incomeHistory:ledger},broker);
assert(out.includes('Past contracts awaiting settlement records (1)'));
assert(out.includes('&lt;script&gt;'));
assert(!out.includes('<script>'));
assert(out.includes('Unreconciled'));
console.log('Options history year separation and reconciliation UI passed');
